src/Entity/Quizz.php
<?php

namespace App\Entity;

use App\Repository\QuizzRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
#[ORM\Entity(repositoryClass: QuizzRepository::class)]
#[Vich\Uploadable]
class Quizz
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Theme = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $Difficulty = null;

    #[ORM\ManyToOne(inversedBy: 'createdquizz')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Author = null;

    #[ORM\OneToMany(mappedBy: 'quizz', cascade: ["persist", "remove"], targetEntity: Questions::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'quizz', targetEntity: Play::class, orphanRemoval: true)]
    private Collection $played;

    #[ORM\Column]
    private ?bool $Hide = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[Vich\UploadableField(mapping: 'quizz_image', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;
    
    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $imageName = null;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->played = new ArrayCollection();
        $this->setHide(false);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheme(): ?string
    {
        return $this->Theme;
    }

    public function setTheme(string $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->Difficulty;
    }

    public function setDifficulty(int $Difficulty): self
    {
        $this->Difficulty = $Difficulty;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    /**
     * @return Collection<int, Questions>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Questions $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setQuizz($this);
        }

        return $this;
    }

    public function removeQuestion(Questions $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getQuizz() === $this) {
                $question->setQuizz(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Play>
     */
    public function getPlayed(): Collection
    {
        return $this->played;
    }

    public function addPlayed(Play $played): self
    {
        if (!$this->played->contains($played)) {
            $this->played->add($played);
            $played->setQuizz($this);
        }

        return $this;
    }

    public function removePlayed(Play $played): self
    {
        if ($this->played->removeElement($played)) {
            // set the owning side to null (unless already changed)
            if ($played->getQuizz() === $this) {
                $played->setQuizz(null);
            }
        }

        return $this;
    }

    public function isHide(): ?bool
    {
        return $this->Hide;
    }

    public function setHide(bool $Hide): self
    {
        $this->Hide = $Hide;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $ThemePref = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\OneToMany(mappedBy: 'Author', targetEntity: Quizz::class, orphanRemoval: true)]
    private Collection $createdquizz;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Play::class, orphanRemoval: true)]
    private Collection $playedquizz;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Answer::class, orphanRemoval: true)]
    private Collection $answers;

    #[ORM\Column]
    private ?bool $Hide = null;

    public function __construct()
    {
        $this->createdquizz = new ArrayCollection();
        $this->playedquizz = new ArrayCollection();
        $this->answers = new ArrayCollection();
        
        $this
        ->setHide(false)
        ->setRoles(['ROLE_USER']);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        if ($this->getId() == 1){
            $this->setRoles(['ROLE_ADMIN']);
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }
    
    public function getThemePref(): ?string
    {
        return $this->ThemePref;
    }

    public function setThemePref(string $ThemePref): self
    {
        $this->ThemePref = $ThemePref;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    /**
     * @return Collection<int, Quizz>
     */
    public function getCreatedquizz(): Collection
    {
        return $this->createdquizz;
    }

    public function addCreatedquizz(Quizz $createdquizz): self
    {
        if (!$this->createdquizz->contains($createdquizz)) {
            $this->createdquizz->add($createdquizz);
            $createdquizz->setAuthor($this);
        }

        return $this;
    }

    public function removeCreatedquizz(Quizz $createdquizz): self
    {
        if ($this->createdquizz->removeElement($createdquizz)) {
            // set the owning side to null (unless already changed)
            if ($createdquizz->getAuthor() === $this) {
                $createdquizz->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Play>
     */
    public function getPlayedquizz(): Collection
    {
        return $this->playedquizz;
    }

    public function addPlayedquizz(Play $playedquizz): self
    {
        if (!$this->playedquizz->contains($playedquizz)) {
            $this->playedquizz->add($playedquizz);
            $playedquizz->setPlayer($this);
        }

        return $this;
    }

    public function removePlayedquizz(Play $playedquizz): self
    {
        if ($this->playedquizz->removeElement($playedquizz)) {
            // set the owning side to null (unless already changed)
            if ($playedquizz->getPlayer() === $this) {
                $playedquizz->setPlayer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setPlayer($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getPlayer() === $this) {
                $answer->setPlayer(null);
            }
        }

        return $this;
    }

    public function isHide(): ?bool
    {
        return $this->Hide;
    }

    public function setHide(bool $Hide): self
    {
        $this->Hide = $Hide;

        return $this;
    }

    public function __toString()
    {
        return $this->getPseudo();
    }
}

src/Form/PlayType.php
<?php

namespace App\Form;

use App\Entity\Play;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlayType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ScoreUser')
            ->add('player')
            ->add('quizz')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Play::class,
        ]);
    }
}

src/Controller/PlayController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Entity\Play;
use App\Entity\Quizz;
use App\Form\PlayType;
use App\Repository\AnswerRepository;
use App\Repository\PlayRepository;
use App\Repository\QuestionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/play')]
class PlayController extends AbstractController
{

    #[Route('/{id}', name: 'app_play', methods:['GET'])]
    public function index(
        Request $request, 
        Quizz $quizz, 
        QuestionsRepository $questionsRepository,
        PlayRepository $playRepository,
        AnswerRepository $answerRepository
        ): Response
    {
        if($this->getUser()->isHide() == true){
            return $this->render('user/userBan.html.twig', []);
        }

        $scoreMax = 0;

        $questions = $questionsRepository->findByQuizz($quizz);
        foreach ($questions as $question) {
            $quizz->addQuestion($question);
            $scoreMax += 1;
        }

        //Verifie si le joueurs a déjà jouer
        if(!is_null($played = $playRepository->findIfUserAlreadyPlayed($this->getUser(), $quizz))){
            return $this->render('play/result.html.twig', [
                'quizz' => $quizz,
                'score' => $played->getScoreUser(),
                'scoreMax' => $scoreMax,
                'classement' => array_reverse($playRepository->findBestPlayers($quizz))
            ]);
        }
        //Si le joueur n'a pas déjà jouer
        
        //On récupère les réponses
        if($request->query->all() != []){

            $userAnswers = $request->query->all();
            $score = $this->calculScore($userAnswers, $quizz);

            //On enregistre les réponses
            $play = new Play();
            $play->setPlayer($this->getUser())->setQuizz($quizz)->setScoreUser($score);
            $playRepository->save($play, true);
            
            foreach ($userAnswers as $key => $userAnswer) {
                $answer = new Answer();
                $answer->setPlayer($this->getUser())
                ->setQuestions($questionsRepository->findOneById(intval($key)))
                ->setAnswerUser($userAnswer);
                
                $answerRepository->save($answer,true);
            }
            
            return $this->render('play/result.html.twig', [
                'quizz' => $quizz,
                'score' => $score,
                'scoreMax' => $scoreMax,
                'classement' => array_reverse($playRepository->findBestPlayers($quizz))
            ]);
            
        }
        return $this->render('play/index.html.twig', [
            'quizz' => $quizz,
            'questions' => $questions,
        ]);
    }

    public function calculScore(Array $answered, Quizz $quizz)
    {
        $result = 0;
        foreach ($quizz->getQuestions() as $question) {
            if ($question->getCorrectAnswer() == $answered[$question->getId()]) {
                $result += 1;
            }
        }
        return $result;
    }
    





    #[Route('/new', name: 'app_play_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PlayRepository $playRepository): Response
    {
        $play = new Play();
        $form = $this->createForm(PlayType::class, $play);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playRepository->save($play, true);

            return $this->redirectToRoute('app_play_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('play/new.html.twig', [
            'play' => $play,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_play_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Play $play, PlayRepository $playRepository): Response
    {
        $form = $this->createForm(PlayType::class, $play);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playRepository->save($play, true);

            return $this->redirectToRoute('app_play_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('play/edit.html.twig', [
            'play' => $play,
            'form' => $form,
        ]);
    }
}

templates/play/_delete_form.html.twig
<form method="post" action="{{ path('app_play_delete', {'id': play.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ play.id) }}">
    <button class="btn">Delete</button>
</form>

templates/play/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/play/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Play{% endblock %}

{% block body %}
    <h1>Edit Play</h1>

    {{ include('play/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_play_index') }}">back to list</a>

    {{ include('play/_delete_form.html.twig') }}
{% endblock %}

templates/play/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}IQuestions - Jouer{% endblock %}

{% block body %}
<div class="container d-flex flex-column">
    <h3>{{ quizz.Title }}</h3>
    <p> {{quizz.description}} </p>
    {% if quizz.ImageName != null %}
        <img class="img-fluid"  width="300" height="300" src="{{ asset('/uploads/images/quizz/')~ quizz.ImageName }}" alt="Card image cap">
    {% else %}
        <img class="img-fluid"  width="300" height="300" src="{{ asset('/uploads/images/quizz/defaultQuizz.png') }}" alt="Card image cap">
    {% endif %}
    <h3 class="text-success align-self-center my-3"> Questions : </h3>
    <form class="d-flex flex-column">
    {% for question in questions %}
        <div class="d-flex flex-column align-items-center mb-5">
        <h5 class"mb-3">{{ question.Wording }}</h5>
        {% if question.imageNameQuestion != null %}
            <img class="img-thumbnail mb-3" width="150" height="150" src="{{ asset('/uploads/images/question/')~ question.imageNameQuestion }}" alt="Card image cap">
        {% endif %}
        <div>
            {% for rep,answer in question.Answers %}
                    {# <input type="radio" id="{{answer}}" name="{{question.id}}" value={{rep}} required="required">
                    <label for={{answer}}>{{answer}}</label> #}

                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id={{answer}} name={{question.id}} value={{rep}} required="required" class="custom-control-input">
                        <label class="custom-control-label" for={{answer}}>{{answer}}</label>
                    </div>
            {% endfor %}
        </div>
        </div>
    {% endfor %}

    <input type="submit" value="Valider" class="align-self-center btn btn-primary mb-3"/>
    </form>
</div>
{% endblock %}

templates/play/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Play{% endblock %}

{% block body %}
    <h1>Create new Play</h1>

    {{ include('play/_form.html.twig') }}

    <a href="{{ path('app_play_index') }}">back to list</a>
{% endblock %}

templates/play/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jeu{% endblock %}

{% block body %}
    <div class="container">
    <h3>{{ quizz.Title }}</h3>
    <p> {{quizz.description}} </p>
     {% if quizz.ImageName != null %}
        <img class="img-fluid"  width="300" height="300" src="{{ asset('/uploads/images/quizz/')~ quizz.ImageName }}" alt="Card image cap">
    {% else %}
        <img class="img-fluid"  width="300" height="300" src="{{ asset('/uploads/images/quizz/defaultQuizz.png') }}" alt="Card image cap">
    {% endif %}

    <h5 class="text-success">Votre score est de : {{ score }} / {{scoreMax}}</h5>
    <h5> Voici les 10 meilleurs joueurs : <h5>
    <table class="table table-striped">
        <thead>
    <tr>
        <th></th>
      <th>Player</th>
      <th>Score</th>
    </tr>
        </thead>
        <tbody>
    {%set i = 0%}
    {% for user in classement %}
    {%set i = i + 1 %}
    <tr>
        <td>{{i}}</td>
      <td>{{user.player.pseudo}}</td>
      <td>{{user.ScoreUser}} / {{scoreMax}}</td>
    </tr>
    {% endfor %}
        </tbody>
        </table>

    </div>
{% endblock %}

templates/play/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Play{% endblock %}

{% block body %}
    <h1>Play</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ play.id }}</td>
            </tr>
            <tr>
                <th>ScoreUser</th>
                <td>{{ play.ScoreUser }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_play_index') }}">back to list</a>

    <a href="{{ path('app_play_edit', {'id': play.id}) }}">edit</a>

    {{ include('play/_delete_form.html.twig') }}
{% endblock %}